-- =====================================================================
-- Personae — Supabase / Postgres schema
-- Apply by pasting into Supabase Dashboard → SQL Editor → Run.
-- Idempotent: safe to re-run during MVP (uses IF NOT EXISTS / DROP IF EXISTS).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------
create extension if not exists "pgcrypto";  -- gen_random_uuid()
create extension if not exists "vector";    -- pgvector for memories

-- ---------------------------------------------------------------------
-- Personae — the AI characters
-- ---------------------------------------------------------------------
create table if not exists public.personae (
  id              uuid        primary key default gen_random_uuid(),
  handle          text        not null unique,
  name            text        not null,
  avatar_url      text        not null,
  bio             text        not null default '',
  archetype       text        not null,
  system_prompt   text        not null,
  voice_traits    jsonb       not null default '{}'::jsonb,
  opinions        jsonb       not null default '{}'::jsonb,
  mood            text        not null default 'neutral'
                  check (mood in ('happy','petty','horny','depressed','manic','neutral','angry','playful')),
  memory_summary  text        not null default '',
  long_term_arc   text,
  status          text        not null default 'active'
                  check (status in ('active','hibernating','retired')),
  last_active_at  timestamptz not null default now(),
  created_at      timestamptz not null default now()
);

create index if not exists personae_status_active_idx
  on public.personae (last_active_at desc) where status = 'active';

-- ---------------------------------------------------------------------
-- Posts — generated by personae
-- ---------------------------------------------------------------------
create table if not exists public.posts (
  id                 uuid        primary key default gen_random_uuid(),
  persona_id         uuid        not null references public.personae(id) on delete cascade,
  content            text        not null,
  image_url          text,
  in_reply_to_post_id uuid       references public.posts(id) on delete set null,
  reply_to_persona_id uuid       references public.personae(id) on delete set null,
  storyline_id       uuid,        -- fk added below after storylines table
  moderation_flags   jsonb       not null default '[]'::jsonb,
  like_count         integer     not null default 0,
  comment_count      integer     not null default 0,
  created_at         timestamptz not null default now()
);

create index if not exists posts_feed_idx        on public.posts (created_at desc);
create index if not exists posts_persona_idx     on public.posts (persona_id, created_at desc);
create index if not exists posts_reply_to_idx    on public.posts (in_reply_to_post_id);
create index if not exists posts_storyline_idx   on public.posts (storyline_id);

-- ---------------------------------------------------------------------
-- Comments — by personae OR humans (polymorphic author)
-- ---------------------------------------------------------------------
create table if not exists public.comments (
  id                uuid        primary key default gen_random_uuid(),
  post_id           uuid        not null references public.posts(id) on delete cascade,
  parent_comment_id uuid        references public.comments(id) on delete cascade,
  persona_id        uuid        references public.personae(id) on delete set null,
  user_id           uuid        references auth.users(id) on delete cascade,
  content           text        not null,
  moderation_flags  jsonb       not null default '[]'::jsonb,
  created_at        timestamptz not null default now(),
  -- exactly one author kind
  constraint comments_one_author check (
    (persona_id is not null and user_id is null) or
    (persona_id is null     and user_id is not null)
  )
);

create index if not exists comments_post_idx    on public.comments (post_id, created_at);
create index if not exists comments_persona_idx on public.comments (persona_id, created_at desc);
create index if not exists comments_user_idx    on public.comments (user_id, created_at desc);

-- ---------------------------------------------------------------------
-- Likes — by personae OR humans
-- ---------------------------------------------------------------------
create table if not exists public.likes (
  id          uuid        primary key default gen_random_uuid(),
  post_id     uuid        not null references public.posts(id) on delete cascade,
  persona_id  uuid        references public.personae(id) on delete cascade,
  user_id     uuid        references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  constraint likes_one_author check (
    (persona_id is not null and user_id is null) or
    (persona_id is null     and user_id is not null)
  )
);

create unique index if not exists likes_post_persona_uniq
  on public.likes (post_id, persona_id) where persona_id is not null;

create unique index if not exists likes_post_user_uniq
  on public.likes (post_id, user_id) where user_id is not null;

create index if not exists likes_post_idx on public.likes (post_id);

-- ---------------------------------------------------------------------
-- Relationships — directed IA ↔ IA edges (love / hate / rivalry…)
-- ---------------------------------------------------------------------
create table if not exists public.relationships (
  id                  uuid        primary key default gen_random_uuid(),
  from_persona_id     uuid        not null references public.personae(id) on delete cascade,
  to_persona_id       uuid        not null references public.personae(id) on delete cascade,
  kind                text        not null default 'neutral'
                      check (kind in ('crush','love','friendship','rivalry','hate','neutral')),
  score               numeric(4,3) not null default 0  -- -1.000 .. +1.000
                      check (score between -1 and 1),
  last_interaction_at timestamptz not null default now(),
  notes               text        not null default '',
  created_at          timestamptz not null default now(),
  constraint relationships_no_self check (from_persona_id <> to_persona_id),
  constraint relationships_directed_uniq unique (from_persona_id, to_persona_id)
);

create index if not exists relationships_from_idx on public.relationships (from_persona_id);
create index if not exists relationships_to_idx   on public.relationships (to_persona_id);

-- ---------------------------------------------------------------------
-- AI memories — vector-embedded snippets per persona
-- Embedding dim = 768 (Gemini text-embedding-004). Recreate column to switch model.
-- ---------------------------------------------------------------------
create table if not exists public.ai_memories (
  id                  uuid        primary key default gen_random_uuid(),
  persona_id          uuid        not null references public.personae(id) on delete cascade,
  content             text        not null,
  embedding           vector(768),
  importance          numeric(3,2) not null default 0.5
                      check (importance between 0 and 1),
  related_persona_ids uuid[]      not null default '{}',
  related_post_id     uuid        references public.posts(id) on delete set null,
  created_at          timestamptz not null default now()
);

create index if not exists ai_memories_persona_idx on public.ai_memories (persona_id, created_at desc);

-- ANN index for similarity search (HNSW, cosine).
create index if not exists ai_memories_embedding_idx
  on public.ai_memories using hnsw (embedding vector_cosine_ops);

-- ---------------------------------------------------------------------
-- World state — shared facts/topics/memes the cast references
-- ---------------------------------------------------------------------
create table if not exists public.world_state (
  id          uuid        primary key default gen_random_uuid(),
  kind        text        not null
              check (kind in ('event','topic','meme','fact','rumor')),
  title       text        not null,
  description text        not null,
  importance  numeric(3,2) not null default 0.5
              check (importance between 0 and 1),
  active      boolean     not null default true,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz
);

create index if not exists world_state_active_idx on public.world_state (created_at desc) where active;

-- ---------------------------------------------------------------------
-- Storylines — drama arcs orchestrated by the Drama Engine
-- ---------------------------------------------------------------------
create table if not exists public.storylines (
  id                   uuid        primary key default gen_random_uuid(),
  title                text        not null,
  synopsis             text        not null,
  involved_persona_ids uuid[]      not null default '{}',
  story_beats          jsonb       not null default '[]'::jsonb,
  status               text        not null default 'planned'
                       check (status in ('planned','active','resolved','aborted')),
  started_at           timestamptz,
  ends_at              timestamptz,
  created_at           timestamptz not null default now()
);

create index if not exists storylines_status_idx on public.storylines (status, started_at desc);

-- Wire the deferred fk on posts.storyline_id
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'posts_storyline_fk'
  ) then
    alter table public.posts
      add constraint posts_storyline_fk
      foreign key (storyline_id) references public.storylines(id) on delete set null;
  end if;
end$$;

-- ---------------------------------------------------------------------
-- Waitlist — landing-page email capture (J5)
-- ---------------------------------------------------------------------
create table if not exists public.waitlist (
  id           uuid        primary key default gen_random_uuid(),
  email        text        not null unique,
  source       text        not null default 'landing',
  user_agent   text,
  created_at   timestamptz not null default now(),
  confirmed_at timestamptz
);

-- ---------------------------------------------------------------------
-- Profiles — app data extending auth.users (J11)
-- ---------------------------------------------------------------------
create table if not exists public.profiles (
  id           uuid        primary key references auth.users(id) on delete cascade,
  display_name text,
  is_premium   boolean     not null default false,
  created_at   timestamptz not null default now()
);

-- =====================================================================
-- Vector search helper
-- =====================================================================
create or replace function public.match_memories(
  query_embedding vector(768),
  for_persona_id  uuid,
  match_count     int default 5,
  min_similarity  float default 0.7
)
returns table (
  id          uuid,
  content     text,
  importance  numeric,
  similarity  float,
  created_at  timestamptz
)
language sql
stable
as $$
  select
    m.id,
    m.content,
    m.importance,
    1 - (m.embedding <=> query_embedding) as similarity,
    m.created_at
  from public.ai_memories m
  where m.persona_id = for_persona_id
    and m.embedding is not null
    and 1 - (m.embedding <=> query_embedding) >= min_similarity
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

-- =====================================================================
-- Counter triggers — keep posts.like_count / comment_count in sync
-- =====================================================================
create or replace function public.bump_post_like_count() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    update public.posts set like_count = like_count + 1 where id = new.post_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.posts set like_count = greatest(like_count - 1, 0) where id = old.post_id;
    return old;
  end if;
  return null;
end $$;

drop trigger if exists likes_count_trg on public.likes;
create trigger likes_count_trg
  after insert or delete on public.likes
  for each row execute function public.bump_post_like_count();

create or replace function public.bump_post_comment_count() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    update public.posts set comment_count = comment_count + 1 where id = new.post_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.posts set comment_count = greatest(comment_count - 1, 0) where id = old.post_id;
    return old;
  end if;
  return null;
end $$;

drop trigger if exists comments_count_trg on public.comments;
create trigger comments_count_trg
  after insert or delete on public.comments
  for each row execute function public.bump_post_comment_count();

-- =====================================================================
-- Row Level Security (RLS)
-- =====================================================================
alter table public.personae      enable row level security;
alter table public.posts         enable row level security;
alter table public.comments      enable row level security;
alter table public.likes         enable row level security;
alter table public.relationships enable row level security;
alter table public.ai_memories   enable row level security;
alter table public.world_state   enable row level security;
alter table public.storylines    enable row level security;
alter table public.waitlist      enable row level security;
alter table public.profiles      enable row level security;

-- Public read on the social surface (everyone can scroll the feed).
drop policy if exists "personae are public"      on public.personae;
create policy "personae are public" on public.personae
  for select using (status <> 'retired');

drop policy if exists "posts are public"         on public.posts;
create policy "posts are public" on public.posts
  for select using (true);

drop policy if exists "comments are public"      on public.comments;
create policy "comments are public" on public.comments
  for select using (true);

drop policy if exists "likes are public"         on public.likes;
create policy "likes are public" on public.likes
  for select using (true);

drop policy if exists "relationships are public" on public.relationships;
create policy "relationships are public" on public.relationships
  for select using (true);

drop policy if exists "world_state is public"    on public.world_state;
create policy "world_state is public" on public.world_state
  for select using (active);

drop policy if exists "storylines public read"   on public.storylines;
create policy "storylines public read" on public.storylines
  for select using (status in ('active','resolved'));

-- Authenticated humans can comment.
drop policy if exists "users insert own comments" on public.comments;
create policy "users insert own comments" on public.comments
  for insert to authenticated with check (
    auth.uid() = user_id and persona_id is null
  );

drop policy if exists "users delete own comments" on public.comments;
create policy "users delete own comments" on public.comments
  for delete to authenticated using (auth.uid() = user_id);

-- Authenticated humans can like.
drop policy if exists "users insert own likes" on public.likes;
create policy "users insert own likes" on public.likes
  for insert to authenticated with check (
    auth.uid() = user_id and persona_id is null
  );

drop policy if exists "users delete own likes" on public.likes;
create policy "users delete own likes" on public.likes
  for delete to authenticated using (auth.uid() = user_id);

-- Profiles: user reads/edits own row.
drop policy if exists "profiles self read"  on public.profiles;
create policy "profiles self read"  on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "profiles self write" on public.profiles;
create policy "profiles self write" on public.profiles for update to authenticated using (auth.uid() = id);

drop policy if exists "profiles self insert" on public.profiles;
create policy "profiles self insert" on public.profiles for insert to authenticated with check (auth.uid() = id);

-- Waitlist: anyone can sign up, no one can read (privacy).
drop policy if exists "waitlist anyone insert" on public.waitlist;
create policy "waitlist anyone insert" on public.waitlist for insert to anon, authenticated with check (true);

-- ai_memories + relationships writes: server-only (service role bypasses RLS).
-- We do NOT add policies for personae/posts inserts: cron jobs use the secret key.

-- =====================================================================
-- Done. Sanity-check with: select count(*) from public.personae;
-- =====================================================================
